name: XpGet
version: 1.3.0
main: com.flyaway.xpget.XpGetPlugin
api-version: 1.21
author: FlyAwayMaking
website: https://github.com/flyawaymaking
description: Конвертация опыта в бутылочки опыта

commands:
  xpget:
    description: Конвертировать опыт в бутылочки опыта
    usage: /<command> [amount/max/reload]
    permission-message: "<red>У вас нет прав для использования этой команды!"

permissions:
  xpget.use:
    description: Позволяет использовать команду /xpget
    default: true
  xpget.reload:
    description: Позволяет перезагружать конфигурацию плагина
    default: op
